import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(r"C:\Users\Samraddhi\OneDrive\Desktop\Sales Transaction datset\sales_raw_data.csv")
df = df.drop_duplicates()
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())
df["Salesperson"] = df["Salesperson"].fillna("Unknown")
df["Customer_Name"] = df["Customer_Name"].str.title()
df["Region"] = df["Region"].str.title()
df["Product"] = df["Product"].str.title()
df["Payment_Status"] = df["Payment_Status"].str.title()
df["Date"] = pd.to_datetime(df["Date"])
df["Quantity"] = df["Quantity"].astype(int)
df["Price"] = df["Price"].astype(float)
df["Total_Sales"] = df["Quantity"] * df["Price"]
df.to_csv("cleaned_data.csv", index=False)
summary = df.describe(include="all")
summary.to_excel("summary_report.xlsx")
plt.figure(figsize=(6,4))
df["Region"].value_counts().plot(kind="bar", color="skyblue")
plt.title("Orders by Region")
plt.xlabel("Region")
plt.ylabel("Number of Orders")
plt.tight_layout()
plt.savefig("region_chart.png")
plt.close()
plt.figure(figsize=(6,4))
df["Product"].value_counts().plot(kind="bar", color="orange")
plt.title("Product Distribution")
plt.xlabel("Product")
plt.ylabel("Orders")
plt.tight_layout()
plt.savefig("product_chart.png")
plt.close()
plt.figure(figsize=(5,5))
df["Payment_Status"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)
plt.ylabel("")
plt.title("Payment Status")
plt.tight_layout()
plt.savefig("payment_chart.png")
plt.close()
plt.figure(figsize=(6,4))
sales = df.groupby("Salesperson")["Total_Sales"].sum()
sales.plot(kind="bar", color="green")
plt.title("Sales by Salesperson")
plt.xlabel("Salesperson")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.savefig("salesperson_chart.png")
plt.close()
print("Data cleaning completed successfully!")
print("Files created:")
print("- cleaned_data.csv")
print("- summary_report.xlsx")
print("- region_chart.png")
print("- product_chart.png")
print("- payment_chart.png")
print("- salesperson_chart.png")